import type { Locale, Level } from "./model";
export const text = {
  pl: {
    timeline: "Pogoda godzina po godzinie",
    timelineHint: "Wybierz godzinę na osi.",
    timelineOverview: "Ryzyko w całej prognozie",
    possibleChanges: "Możliwe zmiany",
    scenarioBand: "Możliwe pogorszenie",
    scenarioBandNote:
      "Przerywane pasmo: możliwe gorsze warunki, nie pewna prognoza.",
    earlier: "Wcześniejsze godziny",
    later: "Późniejsze godziny",
    timelineRisk: [
      "Niskie ryzyko",
      "Możliwe utrudnienia",
      "Wysokie ryzyko",
      "Bardzo trudne",
    ],
    weatherNames: {
      storm: "Burza",
      ice: "Marznący opad",
      snow: "Śnieg",
      fog: "Mgła",
      mist: "Zamglenie",
      rain: "Deszcz",
      limited: "Słaba widoczność",
      lowCloud: "Niskie chmury",
      wind: "Silny wiatr",
      clear: "Bez niskich chmur",
      goodVisibility: "Dobra widoczność",
      unspecified: "Brak opisu zjawisk",
    },
    notReported: "Nie podano w pomiarze",
    noLowCloud: "Bez niskich chmur",
    aboveGround: "Nad lotniskiem",
    gusts: "porywy do",
    runway: "Widoczność na pasie",
    scenarioChanceNote:
      "To szansa na te warunki pogodowe, nie na odwołanie lotu.",
    technical: "Szczegóły dla zainteresowanych",
    travelDirection: "Twój lot",
    plannerHint: "Godzina z biletu.",
    chooseTime:
      "Wybierz godzinę powyżej, aby zobaczyć prognozę dla swojej podróży.",
    levels: "Co oznaczają oceny?",
    levelNotes: [
      "Pogoda nie wskazuje istotnych utrudnień. Lot może być opóźniony z innych przyczyn.",
      "Pogoda może spowolnić obsługę lub utrudnić start i lądowanie.",
      "Warunki mogą istotnie utrudnić start lub lądowanie. Sprawdzaj wiadomości od linii.",
      "Warunki mogą mocno ograniczać loty. O statusie Twojego lotu informuje przewoźnik.",
    ],
    moreHours: "Dalsze godziny",
    weatherForFlights: "Pogoda a loty",
    measurement: "Pomiar na lotnisku",
    ensembleTitle: "Co wskazują inne prognozy?",
    ensembleNote:
      "To warunki sprzyjające mgle, nie jej procentowa szansa. Model obejmuje duży obszar (siatka ok. 25 km).",
    sourceNames: {
      metar: "Pomiar na lotnisku",
      taf: "Prognoza lotniskowa",
      model: "Prognoza komputerowa",
      ensemble: "Warianty prognozy komputerowej",
    },
    title: "Sprawdź pogodę przed lotem.",
    intro: "Mgła, wiatr i widoczność na godzinę Twojego lotu.",
    now: "Warunki teraz",
    arrival: "Przylot",
    departure: "Odlot",
    planner: "Kiedy lecisz?",
    localTime: "Data i godzina lotu",
    check: "Sprawdź warunki",
    forecast: "Szczegóły prognozy",
    unavailable: "Brak aktualnych danych",
    unknown: "Brak oceny",
    caution: "Status Twojego lotu sprawdzisz u przewoźnika.",
    statusLink: "Tablica lotów lotniska",
    updated: "Obserwacja z",
    refresh: "Odśwież",
    refreshing: "Pobieram…",
    failed:
      "Nie udało się odświeżyć. Wyświetlam ostatnie dane z podanym czasem.",
    model: "Prognoza komputerowa · mniej pewna",
    taf: "Prognoza lotniskowa",
    temporary: "Co jeszcze może się zmienić?",
    probability: "Prawdopodobieństwo zjawiska",
    tempo:
      "Takie warunki mogą pojawiać się na krótko. Prognoza nie podaje ich procentowej szansy.",
    transition:
      "Zmiana ma nastąpić w tym przedziale. Nie znamy dokładnej godziny.",
    noSlot:
      "Dla tej godziny nie ma dostępnej prognozy. Wybierz czas w pokazanym zakresie lub sprawdź ponownie bliżej lotu.",
    invalidTime:
      "Sprawdź datę. Godzina w czasie zmiany zegarów może nie istnieć lub występować dwukrotnie; wybierz inną godzinę.",
    pastTime: "Wybierz przyszłą godzinę lotu.",
    share: "Kopiuj link do tej godziny",
    copied: "Link skopiowany",
    copyFailed: "Nie udało się skopiować. Skopiuj adres z przeglądarki.",
    visibility: "Widzialność",
    ceiling: "Podstawa chmur",
    wind: "Wiatr",
    ground: "Na ziemi",
    deicing:
      "Możliwe odladzanie lub obsługa zimowa. Czas oczekiwania zależy od sytuacji na lotnisku.",
    fogPossible:
      "Wilgoć i słaby wiatr sprzyjają mgle. Jej początek jest niepewny.",
    fogIncreasing:
      "Ostatnie pomiary coraz bardziej sprzyjają mgle. Jej początek jest niepewny.",
    improvement: "Prognoza wskazuje poprawę od",
    improvementNote:
      "przez co najmniej 2 godziny. To możliwy okres poprawy pogody, nie godzina wznowienia lotów.",
    sources: "Skąd są dane?",
    fresh: "aktualne",
    stale: "nieaktualne",
    missing: "niedostępne",
    disabled: "wyłączone",
    raw: "Pokaż surowe komunikaty",
    rvrNote:
      "RVR opisuje widzialność wzdłuż pasa. Najniższy odczyt użyty ostrożnie; nie znamy aktywnego pasa ani uprawnień samolotu i załogi. Widzialność METAR nie jest RVR.",
    remind: "Przypomnij przed podróżą",
    calendar: "Dodaj przypomnienie do kalendarza",
    calendarNote:
      "Przypomnienie na 18:00 dzień przed lotem. Gdy ten termin już minął, na 30 minut przed lotem, jeśli jeszcze jest przyszły. Kalendarz nie aktualizuje prognozy automatycznie.",
    push: "Włącz powiadomienia",
    pushNote:
      "Powiadomienie wieczorem przed podróżą i przy wzroście oceny do wysokiej. Na iPhonie dodaj stronę do ekranu początkowego. Wymaga zgody przeglądarki.",
    pushUnavailable: "Powiadomienia przeglądarkowe są obecnie niedostępne.",
    pushSaved: "Powiadomienie zapisane dla tej podróży.",
    pushError:
      "Nie udało się zapisać powiadomienia. Spróbuj ponownie lub użyj kalendarza.",
    pushRemove: "Usuń powiadomienie",
    methodology: "Jak oceniamy pogodę",
    fogGuide: "Mgła w Balicach: co robić przed lotem",
    rights: "Prawa pasażera",
    accuracy: "Jakość prognozy",
    footer:
      "Niezależny serwis. Bez dostępu do statusu konkretnego lotu. Czasy w strefie Europe/Warsaw.",
    limitNote:
      "Ocena dotyczy pogody. Możliwość startu i lądowania zależy też od samolotu, załogi oraz warunków na lotnisku.",
  },
  en: {
    timeline: "Weather hour by hour",
    timelineHint: "Choose a time on the timeline.",
    timelineOverview: "Risk across the forecast",
    possibleChanges: "Possible changes",
    scenarioBand: "Possible worsening",
    scenarioBandNote:
      "Dashed band: worse conditions are possible, not certain.",
    earlier: "Earlier hours",
    later: "Later hours",
    timelineRisk: [
      "Low risk",
      "Possible disruption",
      "High risk",
      "Very challenging",
    ],
    weatherNames: {
      storm: "Thunderstorm",
      ice: "Freezing rain",
      snow: "Snow",
      fog: "Fog",
      mist: "Mist",
      rain: "Rain",
      limited: "Poor visibility",
      lowCloud: "Low clouds",
      wind: "Strong wind",
      clear: "No low clouds",
      goodVisibility: "Good visibility",
      unspecified: "Conditions not specified",
    },
    notReported: "Not reported",
    noLowCloud: "No low clouds",
    aboveGround: "Above the airport",
    gusts: "gusts up to",
    runway: "Runway visibility",
    scenarioChanceNote:
      "This is the chance of these weather conditions, not a flight cancellation.",
    technical: "More about the weather data",
    travelDirection: "Your flight",
    plannerHint: "The time on your ticket.",
    chooseTime: "Choose a time above to see the forecast for your trip.",
    levels: "What do the assessments mean?",
    levelNotes: [
      "The weather does not indicate significant disruption. Other causes may still delay a flight.",
      "The weather may slow ground handling or make takeoff and landing harder.",
      "Conditions may significantly affect takeoff or landing. Check messages from your airline.",
      "Conditions may severely restrict flights. Your airline provides your flight status.",
    ],
    moreHours: "Later hours",
    weatherForFlights: "Weather and flights",
    measurement: "Airport measurement",
    ensembleTitle: "What do other forecasts suggest?",
    ensembleNote:
      "These conditions favour fog; the count is not a percentage chance of fog. The model covers a wide area (about 25 km grid).",
    sourceNames: {
      metar: "Airport measurement",
      taf: "Airport forecast",
      model: "Computer forecast",
      ensemble: "Computer forecast variants",
    },
    title: "Check the weather before you fly.",
    intro: "Fog, wind and visibility at the time of your flight.",
    now: "Conditions now",
    arrival: "Arrival",
    departure: "Departure",
    planner: "When are you flying?",
    localTime: "Flight date and time",
    check: "Check conditions",
    forecast: "Forecast details",
    unavailable: "No current data",
    unknown: "No assessment",
    caution: "Check your airline for your flight status.",
    statusLink: "Airport flight board",
    updated: "Observed at",
    refresh: "Refresh",
    refreshing: "Fetching…",
    failed: "Refresh failed. Showing the last data with its timestamp.",
    model: "Computer forecast · less certain",
    taf: "Airport forecast",
    temporary: "What else could change?",
    probability: "Probability of the weather event",
    tempo:
      "These conditions may occur briefly. The forecast does not give a percentage chance.",
    transition:
      "The change is expected during this interval. The exact time is unknown.",
    noSlot:
      "No forecast is available for this time. Choose a time within the displayed range or check again closer to your flight.",
    invalidTime:
      "Check the date. A clock-change hour can be nonexistent or occur twice; choose another time.",
    pastTime: "Choose a future flight time.",
    share: "Copy a link to this time",
    copied: "Link copied",
    copyFailed: "Could not copy. Copy the address from your browser.",
    visibility: "Visibility",
    ceiling: "Cloud base",
    wind: "Wind",
    ground: "On the ground",
    deicing:
      "Deicing or winter ground handling may be needed. Waiting times depend on airport operations.",
    fogPossible:
      "Humid air and light wind favour fog. Its onset is uncertain.",
    fogIncreasing:
      "Recent measurements increasingly favour fog. Its onset is uncertain.",
    improvement: "The forecast indicates improvement from",
    improvementNote:
      "for at least 2 hours. This is a possible weather improvement window, not a time when flights resume.",
    sources: "Where does the data come from?",
    fresh: "current",
    stale: "outdated",
    missing: "unavailable",
    disabled: "disabled",
    raw: "Show raw reports",
    rvrNote:
      "RVR measures visibility along the runway. The lowest reported reading is used cautiously; the active runway and aircraft/crew capabilities are unknown. METAR visibility is not RVR.",
    remind: "Remind me before travelling",
    calendar: "Add a calendar reminder",
    calendarNote:
      "A reminder at 18:00 on the day before your flight. If that has passed, 30 minutes before departure, when still in the future. The calendar does not update the forecast automatically.",
    push: "Enable notifications",
    pushNote:
      "A reminder on the evening before your trip and when the assessment rises to high. On iPhone, add this site to your Home Screen. Browser permission is required.",
    pushUnavailable: "Browser notifications are currently unavailable.",
    pushSaved: "Notification saved for this trip.",
    pushError: "Could not save a notification. Try again or use your calendar.",
    pushRemove: "Remove notification",
    methodology: "How we assess weather",
    fogGuide: "Fog at Kraków: what to do before flying",
    rights: "Passenger rights",
    accuracy: "Forecast quality",
    footer:
      "Independent service. No access to the status of an individual flight. Times use Europe/Warsaw.",
    limitNote:
      "The assessment covers weather. Takeoff and landing also depend on the aircraft, crew and airport conditions.",
  },
} as const;
const levels = {
  pl: [
    "Niskie ryzyko",
    "Możliwe utrudnienia",
    "Wysokie ryzyko",
    "Bardzo trudne warunki",
  ],
  en: [
    "Low risk",
    "Possible disruption",
    "High risk",
    "Very challenging conditions",
  ],
};
export function levelLabel(level: Level | null, locale: Locale) {
  return level === null ? text[locale].unknown : levels[locale][level - 1];
}
export const reasons: Record<Locale, Record<string, string>> = {
  pl: {
    windShear: "Nagła zmiana wiatru może utrudnić lądowanie",
    heavySnow: "Model wskazuje opad śniegu co najmniej 1 cm/h",
    missing: "Brak wystarczających danych",
    lowRvr: "Słaba widoczność wzdłuż pasa",
    veryLowVisibility: "Bardzo słaba widoczność",
    lowVisibility: "Niska widzialność",
    reducedVisibility: "Obniżona widzialność",
    veryLowCeiling: "Bardzo niskie chmury",
    lowCeiling: "Niskie chmury",
    reducedCeiling: "Nisko wiszące chmury",
    thunderstorm: "Burza: możliwe przerwy w obsłudze lub zmiany podejścia",
    freezingRain: "Marznący opad: ryzyko oblodzenia",
    deicing: "Możliwe odladzanie",
    snow: "Śnieg lub opad zimowy: możliwa wolniejsza obsługa",
    heavyRain: "Silny deszcz",
    crosswind: "Wiatr wieje mocno w poprzek pasa",
    variableWind: "Silny wiatr o zmiennym kierunku może wiać w poprzek pasa",
    strongWind: "Silny wiatr lub porywy",
    rvrBound: "Pomiar widoczności na pasie podaje tylko granicę wartości",
  },
  en: {
    windShear: "Sudden wind changes may make landing harder",
    heavySnow: "Model indicates snowfall of at least 1 cm/h",
    missing: "Insufficient data",
    lowRvr: "Poor visibility along the runway",
    veryLowVisibility: "Very poor visibility",
    lowVisibility: "Low visibility",
    reducedVisibility: "Reduced visibility",
    veryLowCeiling: "Very low clouds",
    lowCeiling: "Low clouds",
    reducedCeiling: "Low-hanging clouds",
    thunderstorm:
      "Thunderstorm: ground handling pauses or approach changes are possible",
    freezingRain: "Freezing precipitation: icing risk",
    deicing: "Deicing may be needed",
    snow: "Snow or wintry precipitation: slower ground handling is possible",
    heavyRain: "Heavy rain",
    crosswind: "Wind is blowing strongly across the runway",
    variableWind:
      "Strong wind with a changing direction may blow across the runway",
    strongWind: "Strong wind or gusts",
    rvrBound:
      "Runway visibility is reported as a bound rather than an exact value",
  },
};
export const slugs = {
  pl: {
    fog: "mgla-balice",
    methodology: "metodologia",
    rights: "prawa-pasazera",
    accuracy: "jakosc-prognozy",
  },
  en: {
    fog: "fog-at-krakow-airport",
    methodology: "methodology",
    rights: "passenger-rights",
    accuracy: "forecast-quality",
  },
} as const;
