name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout the repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node.js version

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build project
        run: npm run build  # Build the project
        env:
          NEXT_PUBLIC_CHECKWX_API_KEY: ${{ secrets.NEXT_PUBLIC_CHECKWX_API_KEY }}
          NEXT_PUBLIC_GA4_KEY: ${{ secrets.NEXT_PUBLIC_GA4_KEY }}
          NEXT_PUBLIC_FLIGHTAWARE_API_KEY: ${{ secrets.NEXT_PUBLIC_FLIGHTAWARE_API_KEY }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

      - name: Deploy to Vercel
        run: npx vercel deploy --prod  # Deploy to Vercel in production mode
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Vercel authentication token
