name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Type check
        run: npx tsc --noEmit
        
      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /krakow-airport
          CHECKWX_API_KEY: ${{ secrets.CHECKWX_API_KEY }}
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out